# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SWINE_GUI\SWINE_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(877, 610)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(877, 610))
        MainWindow.setMaximumSize(QtCore.QSize(877, 610))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../.designer/backup/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(877, 610))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 877, 610))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.h1 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.h1.setMargin(5)
        self.h1.setSpacing(5)
        self.h1.setObjectName(_fromUtf8("h1"))
        self.v1 = QtGui.QVBoxLayout()
        self.v1.setMargin(5)
        self.v1.setSpacing(5)
        self.v1.setObjectName(_fromUtf8("v1"))
        self.lbl_mcstas = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mcstas.sizePolicy().hasHeightForWidth())
        self.lbl_mcstas.setSizePolicy(sizePolicy)
        self.lbl_mcstas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_mcstas.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_mcstas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mcstas.setObjectName(_fromUtf8("lbl_mcstas"))
        self.v1.addWidget(self.lbl_mcstas)
        self.btn_mcstas = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_mcstas.setObjectName(_fromUtf8("btn_mcstas"))
        self.v1.addWidget(self.btn_mcstas)
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.v1.addWidget(self.line_2)
        self.v2 = QtGui.QVBoxLayout()
        self.v2.setMargin(5)
        self.v2.setSpacing(5)
        self.v2.setObjectName(_fromUtf8("v2"))
        self.lbl_instr = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_instr.setEnabled(False)
        self.lbl_instr.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_instr.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_instr.setObjectName(_fromUtf8("lbl_instr"))
        self.v2.addWidget(self.lbl_instr)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rdb_cust = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.rdb_cust.setEnabled(False)
        self.rdb_cust.setAutoExclusive(False)
        self.rdb_cust.setObjectName(_fromUtf8("rdb_cust"))
        self.horizontalLayout.addWidget(self.rdb_cust)
        self.rdb_def = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.rdb_def.setEnabled(False)
        self.rdb_def.setAutoExclusive(False)
        self.rdb_def.setObjectName(_fromUtf8("rdb_def"))
        self.horizontalLayout.addWidget(self.rdb_def)
        self.v2.addLayout(self.horizontalLayout)
        self.line_4 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.v2.addWidget(self.line_4)
        self.lbl_data = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_data.setEnabled(False)
        self.lbl_data.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_data.setObjectName(_fromUtf8("lbl_data"))
        self.v2.addWidget(self.lbl_data)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setMargin(5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_angle = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_angle.setEnabled(False)
        self.lbl_angle.setObjectName(_fromUtf8("lbl_angle"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_angle)
        self.box_angle = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.box_angle.setEnabled(False)
        self.box_angle.setWrapping(False)
        self.box_angle.setFrame(True)
        self.box_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.box_angle.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.box_angle.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.box_angle.setDecimals(2)
        self.box_angle.setMinimum(0.01)
        self.box_angle.setMaximum(179.99)
        self.box_angle.setSingleStep(0.1)
        self.box_angle.setProperty("value", 1.2)
        self.box_angle.setObjectName(_fromUtf8("box_angle"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.box_angle)
        self.lbl_penumbra = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_penumbra.setEnabled(False)
        self.lbl_penumbra.setObjectName(_fromUtf8("lbl_penumbra"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_penumbra)
        self.box_penumbra = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.box_penumbra.setEnabled(False)
        self.box_penumbra.setWrapping(False)
        self.box_penumbra.setFrame(True)
        self.box_penumbra.setAlignment(QtCore.Qt.AlignCenter)
        self.box_penumbra.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.box_penumbra.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.box_penumbra.setDecimals(1)
        self.box_penumbra.setMaximum(999.0)
        self.box_penumbra.setSingleStep(10.0)
        self.box_penumbra.setProperty("value", 80.0)
        self.box_penumbra.setObjectName(_fromUtf8("box_penumbra"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.box_penumbra)
        self.lbl_steps = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_steps.setEnabled(False)
        self.lbl_steps.setObjectName(_fromUtf8("lbl_steps"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_steps)
        self.box_steps = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.box_steps.setEnabled(False)
        self.box_steps.setWrapping(False)
        self.box_steps.setFrame(True)
        self.box_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.box_steps.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.box_steps.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.box_steps.setDecimals(0)
        self.box_steps.setMinimum(5.0)
        self.box_steps.setMaximum(100.0)
        self.box_steps.setSingleStep(5.0)
        self.box_steps.setProperty("value", 50.0)
        self.box_steps.setProperty("showGroupSeparator", False)
        self.box_steps.setObjectName(_fromUtf8("box_steps"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.box_steps)
        self.lbl_neutrons = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_neutrons.setEnabled(False)
        self.lbl_neutrons.setObjectName(_fromUtf8("lbl_neutrons"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_neutrons)
        self.box_neutrons = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.box_neutrons.setEnabled(False)
        self.box_neutrons.setWrapping(False)
        self.box_neutrons.setFrame(True)
        self.box_neutrons.setAlignment(QtCore.Qt.AlignCenter)
        self.box_neutrons.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.box_neutrons.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.box_neutrons.setDecimals(0)
        self.box_neutrons.setMinimum(100000.0)
        self.box_neutrons.setMaximum(100000000.0)
        self.box_neutrons.setSingleStep(100000.0)
        self.box_neutrons.setProperty("value", 1000000.0)
        self.box_neutrons.setObjectName(_fromUtf8("box_neutrons"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.box_neutrons)
        self.v2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_gendata = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_gendata.setEnabled(False)
        self.btn_gendata.setObjectName(_fromUtf8("btn_gendata"))
        self.horizontalLayout_2.addWidget(self.btn_gendata)
        self.txt_description_2 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_description_2.setEnabled(False)
        self.txt_description_2.setObjectName(_fromUtf8("txt_description_2"))
        self.horizontalLayout_2.addWidget(self.txt_description_2)
        self.v2.addLayout(self.horizontalLayout_2)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.v2.addWidget(self.line_3)
        self.lbl_plot = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_plot.setEnabled(True)
        self.lbl_plot.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_plot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_plot.setObjectName(_fromUtf8("lbl_plot"))
        self.v2.addWidget(self.lbl_plot)
        self.btn_data = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_data.setEnabled(True)
        self.btn_data.setObjectName(_fromUtf8("btn_data"))
        self.v2.addWidget(self.btn_data)
        self.lbl_dataset = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_dataset.setEnabled(True)
        self.lbl_dataset.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_dataset.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_dataset.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dataset.setObjectName(_fromUtf8("lbl_dataset"))
        self.v2.addWidget(self.lbl_dataset)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btn_plot = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_plot.setEnabled(True)
        self.btn_plot.setObjectName(_fromUtf8("btn_plot"))
        self.gridLayout_2.addWidget(self.btn_plot, 1, 0, 1, 1)
        self.btn_plot_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_plot_2.setEnabled(True)
        self.btn_plot_2.setObjectName(_fromUtf8("btn_plot_2"))
        self.gridLayout_2.addWidget(self.btn_plot_2, 1, 1, 1, 1)
        self.txt_description = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_description.setEnabled(True)
        self.txt_description.setObjectName(_fromUtf8("txt_description"))
        self.gridLayout_2.addWidget(self.txt_description, 0, 1, 1, 1)
        self.lbl_description = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_description.setEnabled(True)
        self.lbl_description.setObjectName(_fromUtf8("lbl_description"))
        self.gridLayout_2.addWidget(self.lbl_description, 0, 0, 1, 1)
        self.v2.addLayout(self.gridLayout_2)
        self.v1.addLayout(self.v2)
        self.h1.addLayout(self.v1)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.h1.addWidget(self.line)
        self.plt_widget = MatplotlibWidget(self.horizontalLayoutWidget)
        self.plt_widget.setEnabled(False)
        self.plt_widget.setMinimumSize(QtCore.QSize(590, 590))
        self.plt_widget.setMaximumSize(QtCore.QSize(590, 590))
        self.plt_widget.setObjectName(_fromUtf8("plt_widget"))
        self.h1.addWidget(self.plt_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SWINE GUI", None))
        self.lbl_mcstas.setText(_translate("MainWindow", "McStas Version: UNSELECTED", None))
        self.btn_mcstas.setText(_translate("MainWindow", "Select mcstas path", None))
        self.lbl_instr.setText(_translate("MainWindow", "Instrument select:", None))
        self.rdb_cust.setText(_translate("MainWindow", "Custom\n"
"Instrument", None))
        self.rdb_def.setText(_translate("MainWindow", "Default\n"
"Instrument", None))
        self.lbl_data.setText(_translate("MainWindow", "Generating data:", None))
        self.lbl_angle.setText(_translate("MainWindow", "Sample angle:", None))
        self.lbl_penumbra.setText(_translate("MainWindow", "Max penumbra:", None))
        self.lbl_steps.setText(_translate("MainWindow", "No. of steps\n"
"per slit:", None))
        self.lbl_neutrons.setText(_translate("MainWindow", "No. of neutrons\n"
"per simulation:", None))
        self.btn_gendata.setText(_translate("MainWindow", "GENERATE DATA:", None))
        self.lbl_plot.setText(_translate("MainWindow", "Plotting data:", None))
        self.btn_data.setText(_translate("MainWindow", "Load data set", None))
        self.lbl_dataset.setText(_translate("MainWindow", "Data set: UNSELECTED", None))
        self.btn_plot.setText(_translate("MainWindow", "PLOT [s1|s2]", None))
        self.btn_plot_2.setText(_translate("MainWindow", "PLOT [s2|Lum]", None))
        self.lbl_description.setText(_translate("MainWindow", "Plot description:", None))

from MatplotlibWidget import MatplotlibWidget
