# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ISIS STFC\Desktop\SWINE_GUI\SWINE_GUI_cstinstr.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(380, 275)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(380, 275))
        Dialog.setMaximumSize(QtCore.QSize(380, 275))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 230, 361, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setEnabled(True)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 217))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setMargin(5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.btn_select = QtGui.QPushButton(self.formLayoutWidget)
        self.btn_select.setObjectName(_fromUtf8("btn_select"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.btn_select)
        self.lbl_btn = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_btn.setObjectName(_fromUtf8("lbl_btn"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl_btn)
        self.lbl_s1w = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_s1w.setEnabled(True)
        self.lbl_s1w.setObjectName(_fromUtf8("lbl_s1w"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_s1w)
        self.txt_s1w = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_s1w.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_s1w.sizePolicy().hasHeightForWidth())
        self.txt_s1w.setSizePolicy(sizePolicy)
        self.txt_s1w.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_s1w.setProperty("clearButtonEnabled", False)
        self.txt_s1w.setObjectName(_fromUtf8("txt_s1w"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_s1w)
        self.lbl_s2w = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_s2w.setEnabled(True)
        self.lbl_s2w.setObjectName(_fromUtf8("lbl_s2w"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_s2w)
        self.txt_s2w = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_s2w.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_s2w.sizePolicy().hasHeightForWidth())
        self.txt_s2w.setSizePolicy(sizePolicy)
        self.txt_s2w.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_s2w.setObjectName(_fromUtf8("txt_s2w"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_s2w)
        self.lbl_s1p = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_s1p.setEnabled(True)
        self.lbl_s1p.setObjectName(_fromUtf8("lbl_s1p"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_s1p)
        self.txt_s1p = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_s1p.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_s1p.sizePolicy().hasHeightForWidth())
        self.txt_s1p.setSizePolicy(sizePolicy)
        self.txt_s1p.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_s1p.setObjectName(_fromUtf8("txt_s1p"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txt_s1p)
        self.lbl_s2p = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_s2p.setEnabled(True)
        self.lbl_s2p.setObjectName(_fromUtf8("lbl_s2p"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_s2p)
        self.txt_s2p = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_s2p.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_s2p.sizePolicy().hasHeightForWidth())
        self.txt_s2p.setSizePolicy(sizePolicy)
        self.txt_s2p.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_s2p.setObjectName(_fromUtf8("txt_s2p"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txt_s2p)
        self.lbl_sp = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_sp.setEnabled(True)
        self.lbl_sp.setObjectName(_fromUtf8("lbl_sp"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_sp)
        self.lbl_psd = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_psd.setEnabled(True)
        self.lbl_psd.setObjectName(_fromUtf8("lbl_psd"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_psd)
        self.txt_psd = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_psd.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_psd.sizePolicy().hasHeightForWidth())
        self.txt_psd.setSizePolicy(sizePolicy)
        self.txt_psd.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_psd.setObjectName(_fromUtf8("txt_psd"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txt_psd)
        self.txt_sp = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_sp.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_sp.sizePolicy().hasHeightForWidth())
        self.txt_sp.setSizePolicy(sizePolicy)
        self.txt_sp.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_sp.setObjectName(_fromUtf8("txt_sp"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txt_sp)
        self.formLayoutWidget.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_select, self.txt_s1w)
        Dialog.setTabOrder(self.txt_s1w, self.txt_s2w)
        Dialog.setTabOrder(self.txt_s2w, self.txt_s1p)
        Dialog.setTabOrder(self.txt_s1p, self.txt_s2p)
        Dialog.setTabOrder(self.txt_s2p, self.txt_sp)
        Dialog.setTabOrder(self.txt_sp, self.txt_psd)
        Dialog.setTabOrder(self.txt_psd, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Custom instrument select", None))
        self.btn_select.setText(_translate("Dialog", "Select .instr file", None))
        self.lbl_btn.setText(_translate("Dialog", "No file selected...", None))
        self.lbl_s1w.setText(_translate("Dialog", "slit1 width parameter:", None))
        self.lbl_s2w.setText(_translate("Dialog", "slit2 width parameter:", None))
        self.lbl_s1p.setText(_translate("Dialog", "slit1 position parameter:", None))
        self.lbl_s2p.setText(_translate("Dialog", "slit2 position parameter:", None))
        self.lbl_sp.setText(_translate("Dialog", "sample position parameter:", None))
        self.lbl_psd.setText(_translate("Dialog", "PSD_monitor parameter:", None))

